name: askanything
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  bloc: ^8.1.2
  build_runner: ^2.3.1
  shared_preferences: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  either_dart: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
